{% set version = "1.8.0" %}
{% set sha256 = "848c5c7dd3c8acf351546bb523578f06e25d4f45cf3d11e39cf5c2551778d0f7" %}

package:
  name: azure-identity-cpp
  version: {{ version }}

source:
  url: https://github.com/Azure/azure-sdk-for-cpp/archive/refs/tags/azure-identity_{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    # https://github.com/Azure/azure-sdk-for-cpp/issues/4784
    - 0001-remove-wil-from-exported-config.patch

build:
  number: 0
  run_exports:
    - {{ pin_subpackage("azure-identity-cpp", max_pin="x.x.x") }}

# https://github.com/Azure/azure-sdk-for-cpp/blob/main/sdk/identity/azure-identity/vcpkg/vcpkg.json
requirements:
  build:
    - {{ compiler("cxx") }}
    - {{ stdlib("c") }}
    - cmake
    - ninja
  host:
    # azure-core-cpp is pinned in conda-forge-pinning-feedstock
    - azure-core-cpp
    - openssl  # [not win]
    - wil  # [win]

test:
  requires:
    - {{ compiler('cxx') }}
    - cmake
    - ninja
  files:
    - CMakeLists.txt
  commands:
    # shared libs
    - test -f ${PREFIX}/lib/libazure-identity${SHLIB_EXT}   # [unix]
    - if not exist %LIBRARY_BIN%\azure-identity.dll exit 1  # [win]
    - if not exist %LIBRARY_LIB%\azure-identity.lib exit 1  # [win]

    # headers
    - test -f ${PREFIX}/include/azure/identity.hpp          # [unix]
    - if not exist %LIBRARY_INC%\azure\identity.hpp exit 1  # [win]

    # CMake metadata
    - test -f ${PREFIX}/share/azure-identity-cpp/azure-identity-cppTargets.cmake                     # [unix]
    - if not exist %LIBRARY_PREFIX%\share\azure-identity-cpp\azure-identity-cppTargets.cmake exit 1  # [win]

    # CMake find_package()
    - cmake $CMAKE_ARGS -G Ninja -S $RECIPE_DIR -B test-find-package    # [unix]
    - cmake %CMAKE_ARGS% -G Ninja -S %RECIPE_DIR% -B test-find-package  # [win]

about:
  home: https://github.com/Azure/azure-sdk-for-cpp/
  summary: Azure Identity client library for C++
  description: >-
    The Azure Identity library provides Azure Active Directory token authentication support across the Azure SDK. It provides a set of `TokenCredential` implementations which can be used to construct Azure SDK clients which support AAD token authentication.
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE.txt
    - sdk/identity/azure-identity/NOTICE.txt
  doc_url: https://azure.github.io/azure-sdk-for-cpp/
  dev_url: https://github.com/Azure/azure-sdk-for-cpp/tree/main/sdk/identity/azure-identity/

extra:
  recipe-maintainers:
    - teo-tsirpanis
    - jdblischak
    - jjerphan
    - Shelnutt2
